.DEFAULT_GOAL := all
MAKEFLAGS += --warn-undefined-variables --no-print-directory
SHELL := /bin/bash

HOOK :=
IMAGE := musicbrainz-postgres
PLATFORMS ?= amd64
VERSION := 1.0.0-1

include ../buildx/Makefile
