.DEFAULT_GOAL := all
MAKEFLAGS += --warn-undefined-variables --no-print-directory
SHELL := /bin/bash

HOOK := https://hooks.microbadger.com/images/supersandro2000/musicbrainz-postgres/HJw4elCNWPFTAPTTA4X4nvQDPdE=
IMAGE := musicbrainz-postgres
PLATFORMS ?= amd64
VERSION := 12

include ../buildx/Makefile
