FROM {% if arch is defined %}{{arch}}/{% endif %}node:alpine

LABEL maintainer="Sandro Jäckel <sandro.jaeckel@gmail.com>" \
  org.opencontainers.image.created=$BUILD_DATE \
  org.opencontainers.image.authors="Sandro Jäckel <sandro.jaeckel@gmail.com>" \
  org.opencontainers.image.url="https://github.com/SuperSandro2000/docker-images/tree/master/thelounge" \
  org.opencontainers.image.documentation="https://github.com/thelounge/thelounge" \
  org.opencontainers.image.source="https://github.com/SuperSandro2000/docker-images" \
  org.opencontainers.image.version=$VERSION \
  org.opencontainers.image.revision=$REVISION \
  org.opencontainers.image.vendor="SuperSandro2000" \
  org.opencontainers.image.licenses="MIT" \
  org.opencontainers.image.title="TheLounge" \
  org.opencontainers.image.description="Modern, responsive, cross-platform, self-hosted web IRC client"

RUN export user=thelounge \
  && addgroup -S $user && adduser -D -S $user -G $user

COPY [ "files/entrypoint.sh", "/usr/local/bin/" ]

RUN apk add --no-cache --no-progress g++ make python3 su-exec \
  && ln -s /usr/bin/python3 /usr/bin/python \
  && npm install -g --unsafe-perm sqlite3 \
  && apk del g++ make

RUN yarn global add thelounge

ENV THELOUNGE_HOME=/app
EXPOSE 9000
WORKDIR /app
ENTRYPOINT [ "entrypoint.sh" ]
CMD ["thelounge", "start"]
