FROM i386/alpine:3.8

MAINTAINER Sandro Jäckel <sandro.jaeckel@gmail.com>

WORKDIR /usr/src/app

RUN apk add --no-cache -q ca-certificates git jq python2 py-cffi py-cryptography py-lxml py-pip py-yaml \
&& pip install --no-cache-dir -q kibitzr \
&& rm -rf /var/cache/apk/*

COPY ["kibitzr-creds.yml", "kibitzr.yml", "./"]

CMD [ "kibitzr", "run" ]