FROM {% if arch is defined %}supersandro2000/base-alpine:{{arch}}-3.10{% else %}supersandro2000/base-alpine:{{arch}}-3.10{% endif %}

RUN apk add --no-cache --no-progress abuild g++ git make nano

RUN adduser root abuild \
  && abuild-keygen -ain

COPY  [ "files/abuild-alias.sh", "/etc/profile.d/" ]

WORKDIR /git
CMD [ "bash", "--login" ]
